---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook-netlify-dns.selfSignedIssuer" . }}
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    app: {{ include "webhook-netlify-dns.name" . }}
    chart: {{ include "webhook-netlify-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selfSigned: {}

---

# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook-netlify-dns.rootCACertificate" . }}
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    app: {{ include "webhook-netlify-dns.name" . }}
    chart: {{ include "webhook-netlify-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ include "webhook-netlify-dns.rootCACertificate" . }}
  duration: 43800h # 5y
  issuerRef:
    name: {{ include "webhook-netlify-dns.selfSignedIssuer" . }}
  commonName: "ca.webhook-netlify-dns.cert-manager"
  isCA: true

---

# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook-netlify-dns.rootCAIssuer" . }}
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    app: {{ include "webhook-netlify-dns.name" . }}
    chart: {{ include "webhook-netlify-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ca:
    secretName: {{ include "webhook-netlify-dns.rootCACertificate" . }}

---

# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook-netlify-dns.servingCertificate" . }}
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    app: {{ include "webhook-netlify-dns.name" . }}
    chart: {{ include "webhook-netlify-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ include "webhook-netlify-dns.servingCertificate" . }}
  duration: 8760h # 1y
  issuerRef:
    name: {{ include "webhook-netlify-dns.rootCAIssuer" . }}
  dnsNames:
  - {{ include "webhook-netlify-dns.fullname" . }}
  - {{ include "webhook-netlify-dns.fullname" . }}.{{ .Values.certManager.namespace }}
  - {{ include "webhook-netlify-dns.fullname" . }}.{{ .Values.certManager.namespace }}.svc
